### ISSUE TITLE
When using the horn all other functions of the car stop working

### ISSUE THREAD

**Issue by janssens2** [janssens2/MSSE_RC#1]

**Comment by weis0292** [comment]
At first glance, it looks like this issue is caused by the fact that the buzzer uses timer 1 to do it's work.  In our code, we are using timer 1 to control our PID loop, so it would make sense that the PID loop would stop working when the horn is playing.  This could be solved by moving our PID loop to timer 4, as that is the only time left.  If we do that, we should leave a comment about why we are not using timer 1, so Amy knows that we know our stuff.  Below is the link to the Pololu documentation stating the above fact.

https://www.pololu.com/docs/0J18/3

Mike

**Comment by janssens2** [comment]
Made modifications to use TIMER0 instead of TIMER1 and enabled the horn control.  All done in commit 2611ce06be8fb102eb92d6944781426ad1d29d92
